import { Geist, Geist_Mono,Montserrat } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

import { getServerSession } from "next-auth/next";
import { authOptions } from "./api/auth/[...nextauth]/route";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
variable:"--font-Mont",
subsets: ["latin"],

})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async  function RootLayout({ children }) {

  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} bg-white flex justify-center items-center text-black text-lg h-svh`}
      >
         <Providers session={session}>{children}</Providers>
      </body>
    </html>
  );
}
